"use client";

import { Ban, Eye, LoaderCircle, RefreshCw, ShieldCheck, UserRoundCog } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { PortalHeader } from "./PortalHeader";

type User={id:string;name:string;email:string;role:string;banned:boolean;created_at:string;two_factor:boolean};
type Data={users:User[];organizations:Array<{id:string;name:string;members:number}>;classrooms:Array<{id:string;code:string;status:string;domain:string}>};

export function AdminConsole(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [code,setCode]=useState("");const [needsMfa,setNeedsMfa]=useState(false);const [reason,setReason]=useState("");async function load(){setError("");const response=await fetch("/api/admin");const payload=await response.json();if(!response.ok){setError(payload.error??"Support console unavailable");setNeedsMfa(/TOTP|fresh/i.test(payload.error??""));return;}setData(payload);}useEffect(()=>{load()},[]);async function verify(event:FormEvent){event.preventDefault();const response=await fetch("/api/admin/mfa-grant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const payload=await response.json();if(!response.ok)setError(payload.error??"TOTP was not accepted");else{setNeedsMfa(false);setCode("");load();}}async function action(userId:string,action:string){const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,action,reason})});const payload=await response.json();if(!response.ok){setError(payload.error??"Action failed");return;}if(payload.redirect)location.href=payload.redirect;else load();}
  return <main className="portal-page"><PortalHeader/><div className="portal-content"><span className="portal-eyebrow">PLATFORM SUPPORT · AUDITED</span><h1 className="portal-title">Break-glass<br/>operations.</h1><p className="portal-subtitle">Operational metadata only. Student text is unavailable unless an operator starts a reasoned, 15-minute teacher impersonation.</p>{needsMfa&&<form className="portal-form glass-panel" onSubmit={verify} style={{maxWidth:520,padding:24,marginTop:30}}><label>Fresh TOTP code<input inputMode="numeric" maxLength={6} value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,""))}/></label><button className="portal-button" disabled={code.length!==6}><ShieldCheck/> Unlock this operator session</button></form>}{error&&<p className="form-error">{error}</p>}{!data&&!needsMfa&&!error&&<LoaderCircle className="spin"/>}{data&&<><div className="evidence-stats" style={{margin:"35px 0"}}><article><span>Teachers</span><strong>{data.users.length}</strong><small>latest 100 accounts</small></article><article><span>Workspaces</span><strong>{data.organizations.length}</strong><small>self-serve schools</small></article><article><span>Classrooms</span><strong>{data.classrooms.length}</strong><small>operational metadata</small></article></div><section className="settings-panel glass-panel"><h2>Support reason</h2><p>Required before break-glass access. It is written to the immutable audit trail.</p><textarea className="portal-input" rows={2} value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Describe the user-reported issue and why impersonation is necessary…"/><div style={{marginTop:20}}>{data.users.map((user)=><div className="credential-row" key={user.id}><UserRoundCog/><div><b>{user.name} · {user.role}</b><p>{user.email} · {user.banned?"BANNED":"active"} · joined {new Date(user.created_at).toLocaleDateString()}</p></div><button className="portal-button secondary" onClick={()=>action(user.id,user.banned?"unban":"ban")}><Ban/>{user.banned?"Unban":"Ban"}</button><button className="portal-button secondary" onClick={()=>action(user.id,"revoke")}><RefreshCw/>Revoke</button><button className="portal-button" disabled={user.role==="admin"||reason.trim().length<20} onClick={()=>action(user.id,"impersonate")}><Eye/>Access 15m</button></div>)}</div></section></>}</div></main>}
