"use client";

import { Check, KeyRound, LoaderCircle, ShieldCheck, Trash2 } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { authClient, useSession } from "../lib/auth-client";
import { PortalHeader } from "./PortalHeader";

type Credential={id:string;scope:string;last_four:string;verified_at:string;updated_at:string};
type SettingsData={personal:Credential[];shared:Credential[];settings:{default_ai_provider:string}|null;canManageShared:boolean};

export function SettingsPanel(){
  const router=useRouter();const {data,isPending}=useSession();
  const [profile,setProfile]=useState<{membership:{organization_id:string;role:string}|null;profile:{display_name:string;title:string}|null}|null>(null);
  const [settings,setSettings]=useState<SettingsData|null>(null);const [key,setKey]=useState("");const [scope,setScope]=useState<"personal"|"organization">("personal");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const p=await fetch("/api/profile");if(p.status===401){router.replace("/sign-in");return;}const pp=await p.json();if(!pp.membership){router.replace("/onboarding");return;}setProfile(pp);const s=await fetch(`/api/settings/ai?organizationId=${pp.membership.organization_id}`);setSettings(await s.json());},[router]);
  useEffect(()=>{if(!isPending&&!data)router.replace("/sign-in");else if(data)Promise.resolve().then(load);},[data,isPending,load,router]);
  async function saveKey(event:FormEvent){event.preventDefault();if(!profile?.membership)return;setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/settings/ai?organizationId=${profile.membership.organization_id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey:key,scope})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Could not verify key");setKey("");setMessage("OpenAI key verified and encrypted.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save key");}finally{setBusy(false)}}
  async function remove(id:string){if(!profile?.membership)return;const response=await fetch(`/api/settings/ai?organizationId=${profile.membership.organization_id}&id=${id}`,{method:"DELETE"});if(!response.ok){const p=await response.json();setError(p.error??"Could not remove key");}else load();}
  async function setDefault(provider:string){if(!profile?.membership)return;setBusy(true);const response=await fetch(`/api/settings/ai?organizationId=${profile.membership.organization_id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({defaultProvider:provider})});if(response.ok){setMessage("Workspace default updated.");load();}else{const p=await response.json();setError(p.error??"Could not update default");}setBusy(false)}
  async function begin2fa(){setError("");const result=await authClient.twoFactor.enable({});if(result.error){setError(result.error.message??"Could not start TOTP enrollment");return;}const uri=result.data?.totpURI;if(uri){const backup=(result.data as unknown as {backupCodes?:string[]}).backupCodes;if(backup)sessionStorage.setItem("cw-pending-backup-codes",JSON.stringify(backup));await navigator.clipboard.writeText(uri);setMessage("Authenticator setup URI copied. Open it in your authenticator app, then verify from the two-factor page.");router.push("/two-factor?enroll=1");}}
  const credentials=[...(settings?.personal??[]),...(settings?.shared??[])];
  return <main className="portal-page"><PortalHeader/><div className="portal-content"><div className="settings-grid"><aside className="settings-nav"><Link className="active" href="/settings">AI & security</Link><Link href="/settings/workspace">School workspace</Link><Link href="/dashboard">Classrooms</Link><Link href="/privacy">Privacy</Link></aside><section className="settings-panel glass-panel"><span className="portal-eyebrow">TEACHER SETTINGS</span><h2>{profile?.profile?.display_name??"Your account"}</h2><p>Google controls account recovery. CounterWorlds stores no password.</p><hr style={{border:0,borderTop:"1px solid var(--line)",margin:"28px 0"}}/><h2>AI compiler</h2><p>Gemini 2.5 Flash is provided by the platform. OpenAI is optional and uses only a key you explicitly save.</p>{settings?.canManageShared&&<div className="form-grid" style={{margin:"20px 0"}}><button className={`portal-button ${settings.settings?.default_ai_provider==="vertex-gemini"?"":"secondary"}`} onClick={()=>setDefault("vertex-gemini")}><Check/> Gemini default</button><button className={`portal-button ${settings.settings?.default_ai_provider==="openai"?"":"secondary"}`} onClick={()=>setDefault("openai")}><KeyRound/> OpenAI default</button></div>}<form className="portal-form" onSubmit={saveKey}><label>Credential scope<select value={scope} onChange={(event)=>setScope(event.target.value as typeof scope)}><option value="personal">Personal · only my classrooms</option>{settings?.canManageShared&&<option value="organization">School workspace · owners and admins</option>}</select></label><label>OpenAI API key<input type="password" autoComplete="off" value={key} onChange={(event)=>setKey(event.target.value)} placeholder="sk-…"/></label><button className="portal-button" disabled={busy||key.length<20}>{busy?<LoaderCircle className="spin"/>:<KeyRound/>} Test, encrypt, and save</button></form>{credentials.map((credential)=><div className="credential-row" key={credential.id}><KeyRound/><div><b>{credential.scope==="personal"?"Personal":"Workspace"} OpenAI key ····{credential.last_four}</b><p>Verified {new Date(credential.verified_at).toLocaleDateString()} · plaintext is never returned</p></div><button className="portal-button danger" onClick={()=>remove(credential.id)}><Trash2/> Delete</button></div>)}<hr style={{border:0,borderTop:"1px solid var(--line)",margin:"28px 0"}}/><h2>Two-factor security</h2><p>Add a TOTP authenticator and offline backup codes. Platform operators must complete this before opening support tools.</p><button className="portal-button secondary" style={{marginTop:17}} onClick={begin2fa}><ShieldCheck/> Set up authenticator</button>{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success"><Check size={14}/>{message}</p>}</section></div></div></main>;
}
