"use client";

import { Check, Clipboard, LoaderCircle, Shield, Trash2, UserPlus } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "../lib/auth-client";
import { PortalHeader } from "./PortalHeader";

type Member = {id:string;user_id:string;name:string;email:string;role:string;created_at:string};
type Invitation = {id:string;email:string;role:string;status:string;expires_at:string};

export function WorkspacePanel(){
  const router=useRouter();const {data,isPending}=useSession();
  const [organization,setOrganization]=useState<{id:string;name:string;currentUserId:string}|null>(null);
  const [payload,setPayload]=useState<{members:Member[];invitations:Invitation[];canManage:boolean;currentRole:string}|null>(null);
  const [invite,setInvite]=useState({email:"",role:"member"});const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const profile=await fetch("/api/profile");if(profile.status===401){router.replace("/sign-in");return;}const pp=await profile.json();if(!pp.membership){router.replace("/onboarding");return;}setOrganization({id:pp.membership.organization_id,name:pp.membership.name,currentUserId:pp.user.id});const response=await fetch(`/api/organization?organizationId=${pp.membership.organization_id}`);const body=await response.json();if(!response.ok){setError(body.error??"Could not load workspace");return;}setPayload(body);},[router]);
  useEffect(()=>{if(!isPending&&!data)router.replace("/sign-in");else if(data)Promise.resolve().then(load);},[data,isPending,load,router]);
  async function createInvite(event:FormEvent){event.preventDefault();if(!organization)return;setBusy(true);setError("");setMessage("");const response=await fetch(`/api/organization?organizationId=${organization.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(invite)});const body=await response.json();if(!response.ok){setError(body.error??"Could not create invitation");setBusy(false);return;}const link=`${location.origin}${body.path}`;await navigator.clipboard.writeText(link);setInvite({email:"",role:"member"});setMessage(`Invitation link copied for ${body.invitation.email}.`);setBusy(false);load();}
  async function update(body:Record<string,string>){if(!organization)return;setError("");const response=await fetch(`/api/organization?organizationId=${organization.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setError(result.error??"Could not update workspace");return;}load();}
  async function copy(id:string){await navigator.clipboard.writeText(`${location.origin}/accept-invitation/${id}`);setMessage("Invitation link copied.");}
  return <main className="portal-page"><PortalHeader/><div className="portal-content"><div className="settings-grid"><aside className="settings-nav"><Link href="/settings">AI & security</Link><Link className="active" href="/settings/workspace">School workspace</Link><Link href="/dashboard">Classrooms</Link></aside><section className="settings-panel glass-panel"><span className="portal-eyebrow">SCHOOL WORKSPACE</span><h2>{organization?.name??"Loading…"}</h2><p>Owners and admins can copy exact-email invitation links. No student work is exposed here.</p>{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success"><Check size={14}/>{message}</p>}{payload?.canManage&&<form className="portal-form" onSubmit={createInvite} style={{marginTop:24}}><div className="form-grid"><label>Teacher Google email<input type="email" required value={invite.email} onChange={(event)=>setInvite({...invite,email:event.target.value})} placeholder="teacher@school.edu"/></label><label>Workspace role<select value={invite.role} onChange={(event)=>setInvite({...invite,role:event.target.value})}><option value="member">Teacher</option>{payload.currentRole==="owner"&&<option value="admin">Administrator</option>}</select></label></div><button className="portal-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<UserPlus/>} Create and copy invitation</button></form>}<hr style={{border:0,borderTop:"1px solid var(--line)",margin:"28px 0"}}/><h2>People</h2>{payload?.members.map((member)=><div className="credential-row" key={member.id}><Shield/><div><b>{member.name}</b><p>{member.email} · {member.role==="member"?"teacher":member.role}</p></div>{payload.currentRole==="owner"&&member.role!=="owner"&&<><select aria-label={`Role for ${member.name}`} value={member.role} onChange={(event)=>update({memberId:member.id,role:event.target.value,action:"role"})}><option value="member">Teacher</option><option value="admin">Admin</option></select><button className="portal-button danger" onClick={()=>update({memberId:member.id,action:"remove"})}><Trash2/> Remove</button></>}</div>)}{payload?.invitations.length?<><h2 style={{marginTop:30}}>Pending invitations</h2>{payload.invitations.map((item)=><div className="credential-row" key={item.id}><UserPlus/><div><b>{item.email}</b><p>{item.role==="member"?"teacher":item.role} · expires {new Date(item.expires_at).toLocaleDateString()}</p></div><button className="portal-button secondary" onClick={()=>copy(item.id)}><Clipboard/> Copy link</button>{payload.canManage&&<button className="portal-button danger" onClick={()=>update({invitationId:item.id,action:"cancel-invitation"})}>Cancel</button>}</div>)}</>:null}</section></div></div></main>;
}
